# 학습 목표

- TensorFlow 2.0 간단 사용법

In [1]:
import numpy as np
import tensorflow as tf

# Tensor 생성

- []
    - List 생성

In [2]:
[1,2,3]

[1, 2, 3]

In [3]:
[[1,2,3],[4,5,6]]

[[1, 2, 3], [4, 5, 6]]

### Array 생성

- tuple이나 list 둘 다 np.array()로 씌어서 array를 만들 수 있음

In [4]:
arr = np.array([1,2,3])
arr.shape

(3,)

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

### Tensor 생성

- tf.constant()
    - list -> Tensor

In [6]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

- tf.constant()
    - tuple -> Tensor

In [10]:
tf.constant(((1,2,3),(4,5,6)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

- tf.constant()
    - Array -> Tensor

In [11]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [13]:
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

### Tensor에 담긴 정보 확인

- shape 확인

In [14]:
tensor.shape

TensorShape([3])

- data type 확인
    - 주의: Tensor 생성 할 때도 data type을 정해주지 않기 때문에 data type에 대한 혼동이 올 수 있음
    - Data Type에 따라 모델의 무게나 성능 차이에도 영향을 줄 수 있음

In [15]:
tensor.dtype

tf.int64

- data type 정의

In [18]:
tensor = tf.constant([1,2,3],dtype=tf.int32)
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

- data type 변환
    - Numpy에서 astype()을 주었듯이, TensorFlow에서는 tf.cast를 사용

In [20]:
arr = np.array([1,2,3],dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

In [21]:
# np 데이터 변환
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

In [22]:
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [23]:
# tensor 형변환
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

- Tensor에서 Numpy 불러오기
    - .numpy()

In [24]:
tensor.numpy()

array([1, 2, 3], dtype=int32)

- Tensor에서 Numpy 불러오기
    - np.array()

In [25]:
np.array(tensor)

array([1, 2, 3], dtype=int32)

type()를 사용하여 numpy array로 변환된 것 확인

In [26]:
type(tensor)

tensorflow.python.framework.ops.EagerTensor

In [27]:
type(np.array(tensor))

numpy.ndarray

## 난수 생성

- Normal Distribution은 중심극한 이론에 의한 연속적인 모양   
- Uniform Distribution은 중심 극한 이론과는 무관하며 불연속적이며 일정한 분포

- numpy에서는 normal distribution을 기본적으로 생성
    - np.random.randn()

In [28]:
np.random.randn(9)

array([ 1.0319905 ,  0.0021389 ,  1.02205388,  1.31691005, -0.20841443,
        0.42728301,  1.90090973,  1.37595277,  0.76260762])

- tf.random.normal
    - TensorFlow에서 Normal Distribution

In [30]:
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.73522   ,  1.0808449 , -1.1449935 ],
       [ 0.3311494 , -0.05005472,  0.6569032 ],
       [ 0.44760668,  0.38486323, -2.3020544 ]], dtype=float32)>

- tf.random.uniform
    - TensorFlow에서 Uniform Distribution

In [31]:
tf.random.uniform([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.7285445 , 0.9524797 , 0.04952562],
       [0.7825781 , 0.01165473, 0.838302  ],
       [0.99261487, 0.7068262 , 0.9145044 ]], dtype=float32)>