# Numpy Basic

In [1]:
import numpy as np

## data type

array의 dtype을 본다. 

In [3]:
arr = np.array([[1,2,3],[1,2,3]])
arr.dtype

dtype('int64')

In [10]:
# 바로 적용 가능
arr1 = np.array([[1,2,3],[1,2,3]], dtype=np.float32)
arr1.dtype

dtype('float32')

In [4]:
arr.shape

(2, 3)

.astype()으로 datatype을 변환 가능

In [7]:
arr = arr.astype('int32')
arr

array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)

In [8]:
arr.dtype

dtype('int32')

len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

In [11]:
# 차원의 수 확인
arr.ndim

2

In [12]:
len(arr.shape)

2

size 확인

In [13]:
arr.size

6

dtype 확인

In [14]:
arr.dtype

dtype('int32')

## Reshape

In [15]:
arr.shape

(2, 3)

Reshape 

In [16]:
# 사이즈는 그대로 유지해야함
arr.reshape([1,6])

array([[1, 2, 3, 1, 2, 3]], dtype=int32)

In [17]:
arr = np.array([[1,2,3],[4,5,6]])

In [21]:
arr.reshape([3,2])

array([[1, 2],
       [3, 4],
       [5, 6]])

Reshape, -1 활용

In [26]:
arr = arr.reshape(-1)
arr.shape

(6,)

In [27]:
arr = arr.reshape(-1,3)
arr.shape

(2, 3)

random array 생성

In [28]:
arr = np.random.randn(8,8)
arr.shape

(8, 8)

In [32]:
arr = arr.reshape([16,4])
arr.shape

(16, 4)

3차원으로 늘리기

In [35]:
arr = arr.reshape(-1, 2, 1)
arr.shape

(32, 2, 1)

## Ravel
- 다차원 데이터를 1차원 데이터로 읽기

In [46]:
arr=arr.ravel()
arr

array([ 1.10864922, -0.91442522, -1.97296687,  1.53928741,  1.57652558,
        0.44035965, -0.64013372, -0.01458936, -1.8051189 , -1.50628265,
        0.08876298,  1.0421772 , -0.92401358, -1.32707288, -0.63574216,
       -0.36784814,  1.29168626, -0.69490068, -1.17684901,  1.74577073,
        0.16476395,  0.2090322 ,  0.38086025, -0.8267012 , -0.78720869,
       -1.72731254, -0.3980701 , -0.87675149,  1.2896777 ,  0.29434836,
        0.13300819, -1.16162106, -0.27388662,  1.05076968, -2.05891432,
        0.29415054,  0.40161108,  1.18936528, -0.21116425,  0.6625217 ,
        1.13286434,  0.72611663,  0.73144354,  1.0894925 , -0.33852563,
        0.85175356, -1.55403693,  1.39755777,  0.02346707, -1.87775859,
       -0.78829094, -0.9770628 ,  0.51571481,  1.10357378, -0.80983281,
       -0.91361635,  0.60631561,  0.49702316, -0.66290158,  1.41376202,
       -0.09031093, -1.01954119, -0.66957514,  1.86251453])

In [ ]:
arr.ravel().shape

arr의 차원을 1로 바꿔줌  
나중에 배울 layer를 flatten 할 때 같은 기능이라 생각하면 됨 

In [40]:
# arr.reshape(-1) 와 같음
arr.ravel() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음  
이럴 때 사용하는 것이 expand_dims  

In [43]:
arr.shape

(64,)

In [52]:
# np.expand_dims 0은 앞에 생성
arr1 = np.expand_dims(arr,0)
arr1.shape

(1, 64)

In [54]:
# 1은 뒤에 생성
arr2 = np.expand_dims(arr,-1)
arr2.shape

(64, 1)

In [50]:
arr3 = np.expand_dims(np.expand_dims(arr,-1),0)
arr3.shape

(1, 64, 1)

## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [56]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
zeros = np.zeros(1)
zeros

array([0.])

In [60]:
ones = np.ones([5,2])
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [61]:
ones * 5

array([[5., 5.],
       [5., 5.],
       [5., 5.],
       [5., 5.],
       [5., 5.]])

In [62]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [63]:
np.arange(4,9)

array([4, 5, 6, 7, 8])

In [68]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Index

In [65]:
nums = [1,2,3,4,5]

In [67]:
nums[2:]

[3, 4, 5]

In [72]:
# [3,4,5] 가져오기
arr[1]

array([3, 4, 5])

In [76]:
print(arr[1,2])
print(arr[1][2])

5
5


# Slicing

In [77]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [78]:
arr[1:,1:]

array([[4, 5],
       [7, 8]])

In [79]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Boolean Indexing

In [86]:
data =  np.random.randn(3,3)
data

array([[ 1.18970871e-03,  7.32983528e-01, -3.59358329e-01],
       [-7.50288174e-02, -1.84758737e+00, -1.03653176e-01],
       [ 2.30821418e-01,  1.40324657e+00,  4.50252129e-01]])

In [87]:
data <= 0

array([[False, False,  True],
       [ True,  True,  True],
       [False, False, False]])

In [88]:
# True인 부분만 추출
data[data <= 0]

array([-0.35935833, -0.07502882, -1.84758737, -0.10365318])

# Broadcast

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

In [90]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [94]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
arr + np.array([1,1,1])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Math Function

In [95]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [96]:
# 같은 shape 끼리 덧셈가능
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [97]:
np.add(arr,1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
np.multiply(arr,3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [125]:
# 0부터 2사이의 숫자로 만듬
arr = np.random.randint(2, size=27).reshape(3,3,3)
arr_2 = np.random.randint(2, size=9).reshape(3,3)

In [129]:
arr

array([[[0, 0, 1],
        [1, 1, 0],
        [1, 0, 0]],

       [[0, 1, 1],
        [1, 1, 1],
        [0, 0, 0]],

       [[1, 1, 0],
        [0, 1, 0],
        [1, 0, 1]]])

In [131]:
arr_2

array([[1, 1, 0],
       [0, 0, 1],
       [0, 1, 1]])

In [130]:
# 모든 값을 더함
np.sum(arr)

14

In [132]:
arr + arr_2

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 2, 1],
        [1, 1, 2],
        [0, 1, 1]],

       [[2, 2, 0],
        [0, 1, 1],
        [1, 1, 2]]])

In [149]:
arr[2]

array([[1, 1, 0],
       [0, 1, 0],
       [1, 0, 1]])

In [152]:
sum(arr[0])+sum(arr_2[0])

array([4, 3, 3])

In [153]:
sum(arr[0]+arr_2[0])

array([5, 4, 1])

In [120]:
arr = np.array([1,2,3,2,3,4,5])
arr

array([1, 2, 3, 2, 3, 4, 5])

In [121]:
# 가장 큰 값을 가지는 인덱스 번호 반환
np.argmax(arr)

6

In [122]:
np.argmin(arr)

0

In [123]:
# 중복값 제거
np.unique(arr)

array([1, 2, 3, 4, 5])