# PyTorch Basic

PyTorch 기초 사용법

In [1]:
import numpy as np

import torch

In [2]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
nums = torch.arange(9)
print(nums, nums.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]) torch.Size([9])


In [6]:
type(nums)

torch.Tensor

In [7]:
# 넘파이로 변환
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
nums.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
randoms = torch.rand((3,3))
randoms

tensor([[0.7692, 0.7204, 0.6045],
        [0.7754, 0.9721, 0.5521],
        [0.5627, 0.5689, 0.6944]])

In [11]:
zeros = torch.zeros((3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
ones = torch.ones((3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
# 똑같은 shape을 가진 zeros 만들기
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
zeros.size()

torch.Size([3, 3])

# Operations

PyTorch로 수학연산

In [16]:
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [18]:
nums = nums.reshape((3,3))
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [22]:
nums + nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [25]:
# 덧셈
result = torch.add(nums,10)

In [26]:
result.numpy()

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [33]:
result[0]

tensor([10, 11, 12])

## View

In [28]:
range_nums = torch.arange(9).reshape((3,3))
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [29]:
# reshape과 동일한 기능
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
range_nums.view(1,9)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

# Slice and Index

In [31]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [32]:
# 2행 데이터 가져오기
nums[1]

tensor([3, 4, 5])

In [34]:
nums[1:,1:]

tensor([[4, 5],
        [7, 8]])

## Compile

numpy를 torch tensor로 불러오기

In [36]:
arr = np.array([1,1,1])
arr

array([1, 1, 1])

In [37]:
arr_torch = torch.from_numpy(arr)

In [38]:
arr_torch

tensor([1, 1, 1])

In [40]:
# float로 변경
arr_torch.float()

tensor([1., 1., 1.])

In [43]:
# gpu가 있으면 gpu사용
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

# AutoGrad

In [52]:
x = torch.ones(2,2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [53]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [54]:
print(y.grad_fn)

In [55]:
z = y*y*3
out = z.mean()

In [56]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [57]:
out.backward()

In [62]:
# 어떤 스칼라 값에 대한 x의 변화도를 갖는 Tensor
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [63]:
print(x.requires_grad)
print((x ** 2).requires_grad)

True
True


In [64]:
# 기울기를 구하지 않음 (작업속도가 빠름)
with torch.no_grad():
    print((x ** 2).requires_grad)

False
